### ISSUE TITLE
Errors on drag and drop in task editor (edit survey flow)

### ISSUE THREAD

**Issue by os-micmec** [google/ground-platform#1208]
It works one time, but second time I get the error:

```
ERROR TypeError: task.copyWith is not a function
    at edit-job.component.ts:135:23
    at updateInDeeply (immutable.es.js:2103:20)
    at updateInDeeply (immutable.es.js:2116:21)
    at updateIn$1 (immutable.es.js:2081:22)
    at update$1 (immutable.es.js:2152:10)
    at List.update (immutable.es.js:2158:7)
    at EditJobComponent.drop (edit-job.component.ts:133:8)
    at EditJobComponent_Template_div_cdkDropListDropped_1_listener (edit-job.component.html:3:59)
    at executeListenerWithErrorHandling (core.mjs:13975:16)
    at Object.wrapListenerIn_markDirtyAndPreventDefault [as next] (core
```

**Comment by gino-m** [comment]
@rfontanarosa In case you have any ideas
