### ISSUE TITLE
"Continue" button in create flow task editor has no effect

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1301]
```
loading-state.model.ts:1 ERROR Error: Uncaught (in promise): FirebaseError: [code=permission-denied]: Missing or insufficient permissions.
FirebaseError: Missing or insufficient permissions.
    at resolvePromise (zone.js:1265:35)
    at zone.js:1172:21
    at zone.js:1188:37
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _throw (asyncToGenerator.js:25:1)
    at _ZoneDelegate.invoke (zone.js:412:30)
    at Object.onInvoke (core.mjs:24210:33)
    at _ZoneDelegate.invoke (zone.js:411:56)
    at Zone.run (zone.js:169:47)
    at zone.js:1329:38
```

@os-micmec

**Comment by gino-m** [comment]
"Continue" started working once the permissions issue was fixed, but there is an underlying issue related to error handling - create survey flow still shows for unauthenticated users or when user doesn't have permission to write.

**Comment by gino-m** [comment]
@DaoyuT FYI related to #931.

**Comment by gino-m** [comment]
@rfontanarosa Still not seeing the "permission denied" screen when I don't have permission to access a survey.
