### ISSUE TITLE
[Submission list] Panel blank on click of some LOIs

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1585]
Exception in console:

```
navigation.service.ts:118 ERROR TypeError: Cannot read properties of undefined (reading 'geometry')
    at LocationOfInterestService.getLatLngBoundsFromLois (loi.service.ts:84:16)
    at MapComponent.fitMapToLocationsOfInterest (map.component.ts:353:45)
    at MapComponent.selectPolygons (map.component.ts:568:11)
    at MapComponent.selectLocationOfInterest (map.component.ts:524:3)
    at Object.next (map.component.ts:123:3)
    at ConsumerObserver.next (Subscriber.js:113:33)
    at Subscriber._next (Subscriber.js:80:26)
    at Subscriber.next (Subscriber.js:51:18)
    at combineLatest.js:51:40
    at OperatorSubscriber._this._next (OperatorSubscriber.js:33:21)
```

URI: `/survey/45Ub6USuYc5OANM93hEu#f=null&o=null&t=o05SZrYXTSjzSJrCLpCr`

I suspect invalid data caused `getLatLngBoundsFromLois` to fail, leading to the `null`s in the URL.

**Comment by gino-m** [comment]
This was fixed by @amysorto in #1604.
