### ISSUE TITLE
[Layer dialog] Some layers cannot be saved

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#330]
This may be caused by layers that were added before we implemented "index". Is there a way to fall back to some default behavior when index is missing?

Exception:
```
core.js:6228 ERROR FirebaseError: Function DocumentReference.update() called with invalid data. Unsupported field value: undefined (found in field layers.layer001.forms.form001.elements.elementt003.index)
    at new n (http://localhost:4200/vendor.js:163148:23)
    at t.dc (http://localhost:4200/vendor.js:172401:16)
    at http://localhost:4200/vendor.js:172605:17
    at Mr (http://localhost:4200/vendor.js:172606:6)
    at http://localhost:4200/vendor.js:172615:17
    at I (http://localhost:4200/vendor.js:163536:68)
    at Fr (http://localhost:4200/vendor.js:172614:56)
    at Mr (http://localhost:4200/vendor.js:172517:61)
    at http://localhost:4200/vendor.js:172615:17
    at I (http://localhost:4200/vendor.js:163536:68)
defaultErrorLogger @ core.js:6228
handleError @ core.js:6281
handleError @ core.js:13827
executeListenerWithErrorHandling @ core.js:21809
wrapListenerIn_markDirtyAndPreventDefault @ core.js:21848
schedulerFn @ core.js:37171
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:37079
onSubmit @ forms.js:6417
NgForm_submit_HostBindingHandler @ forms.js:6460
executeListenerWithErrorHandling @ core.js:21806
wrapListenerIn_markDirtyAndPreventDefault @ core.js:21848
(anonymous) @ platform-browser.js:976
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:41632
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
invokeTask @ zone-evergreen.js:480
invokeTask @ zone-evergreen.js:1621
globalZoneAwareCallback @ zone-evergreen.js:1647
```

**Comment by gino-m** [comment]
We can assign a temporary value on save.
